<?php

namespace AppBundle\Repository;

/**
 * BirdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BirdRepository extends \Doctrine\ORM\EntityRepository
{


	public function getFamilleBuilder()
  {
  	$qb = $this->createQueryBuilder('c');

  	$qb->select('DISTINCT c.famille')
  	->orderBy('c.famille', 'ASC');
	   
	 return $qb; 
  }

}
