<?php

namespace FT\OrnitBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ObservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObservationRepository extends EntityRepository
{
}
