<?php

namespace FT\OrnitBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ObservationImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObservationImageRepository extends EntityRepository
{
}
